// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservas.Infraestructure.EF.Contexts;

namespace Reservas.Infraestructure.EF.Migrations
{
    [DbContext(typeof(ReadDBContext))]
    partial class ReadDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reservas.Infraestructure.EF.ReadModel.DetalleReservaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("DateTime")
                        .HasColumnName("fechaReserva");

                    b.Property<decimal>("Importe")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("importe");

                    b.Property<int>("NumTicket")
                        .HasColumnType("int")
                        .HasColumnName("numTicket");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("DetalleReserva");
                });

            modelBuilder.Entity("Reservas.Infraestructure.EF.ReadModel.ReservaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdReserva")
                        .HasMaxLength(6)
                        .HasColumnType("int")
                        .HasColumnName("idReserva");

                    b.HasKey("Id");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Reservas.Infraestructure.EF.ReadModel.DetalleReservaReadModel", b =>
                {
                    b.HasOne("Reservas.Infraestructure.EF.ReadModel.ReservaReadModel", "Reserva")
                        .WithMany("Detalle")
                        .HasForeignKey("ReservaId");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Reservas.Infraestructure.EF.ReadModel.ReservaReadModel", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
